_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 3
                - 8
                - 16
                - 55
                - 62
            "4": 3.11.9
            "5": 0.20.1
            "8":
                - 3
            "10":
                - 9
                - 17
            "12": 0.20.1
            "13": windows-amd64
architecture:
    value: sequential
batch_size:
    value: 32
epochs:
    value: 7
